### ISSUE TITLE
Dynamic Schema "Error: schema should be object or boolean"

### ISSUE THREAD

**Issue by ssbothwell** [JouzaLoL/express-json-validator-middleware#20]
I'm trying to use dynamic schemas as described in the documentation:

```
  function loadAccountSchema(req, res, next) {

    try {
      if (req.body.accountType === 'personal') {
        req.schema = accountSchema.Insert;
      }
      else {
        req.schema = accountSchema.InsertCorporate;
      }
      next();
    } catch (error) {
      next(error);
    }
  }

  function getSchema(req) {
  	// return the schema from the previous middleware or the default schema
      return req.schema || DefaultSchema;
  }


  app.post('/account/:uId', loadAccountSchema, validate({ body: getSchema }), function(
    req, res ) {

```

However I get this error when I try to run express:

```
/home/solomon/Development/trippinc/firebase-backend/src/main/functions/node_modules/ajv/lib/ajv.js:303
    throw new Error('schema should be object or boolean');
    ^

Error: schema should be object or boolean
    at Ajv._addSchema (/home/solomon/Development/trippinc/firebase-backend/src/main/functions/node_modules/ajv/lib/ajv.js:303:11)
    at Ajv.compile (/home/solomon/Development/trippinc/firebase-backend/src/main/functions/node_modules/ajv/lib/ajv.js:117:24)
    at Validator.<anonymous> (/home/solomon/Development/trippinc/firebase-backend/src/main/functions/node_modules/express-json-validator-middleware/src/index.js:24:36)
    at Array.map (native)
    at Validator.validate (/home/solomon/Development/trippinc/firebase-backend/src/main/functions/node_modules/express-json-validator-middleware/src/index.js:22:50)
    at module.exports (/home/solomon/Development/trippinc/firebase-backend/src/main/functions/usermgmt.js:86:48)
```
Any ideas whats going on?

**Comment by JouzaLoL** [comment]
Hi, could you please set up a reproduction repo, or a link to your project if it's open source?

**Comment by JouzaLoL** [comment]
Fixed the error in README, closing this, if error persists, I'll reopen.
