### ISSUE TITLE
Error when starting an express server

### ISSUE THREAD

**Issue by AarRidho** [JouzaLoL/express-json-validator-middleware#29]
Hi! I would like to ask about this Error i'm currently having on my project.

```javascript
const validateFunctions = Object.keys(options).map(function (requestProperty) {
                                                      ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Validator.validate (C:\xampp\htdocs\siakad-new\node_modules\express-json-validator-middleware\src\index.js:24:42)
    at Object.<anonymous> (C:\xampp\htdocs\siakad-new\routes\users_route.js:25:54)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
[nodemon] app crashed - waiting for file changes before starting...
```

I tried to do exactly the same approach like in the README, but still got this Error.

```javascript
const { validate } = require('../config/validator');

router.get('/:id', validate({ params: UsersSchema.getUsersById.params }), validate(UsersSchema.getUserById), UsersController.getUserById);
```

Am i missing something here actually?

Any replies would be helpful.

**Comment by AarRidho** [comment]
I'm sorry, this was my fault actually...

i called the ```validate()``` function 2x on the route

Thanks for this great library
